// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhnepo17M88QhxDOlL3aI06qVdjmLHKZg',
    appId: '1:769073984988:web:0cf1470cfb0eb4c2a40b19',
    messagingSenderId: '769073984988',
    projectId: 'novelora-project',
    authDomain: 'novelora-project.firebaseapp.com',
    storageBucket: 'novelora-project.firebasestorage.app',
    measurementId: 'G-R7MN6TERJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGKuqg8PERiQHPn3I7k1-VLmDwH7vwBN0',
    appId: '1:769073984988:android:87a0f052db2caf11a40b19',
    messagingSenderId: '769073984988',
    projectId: 'novelora-project',
    storageBucket: 'novelora-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvXY-qT2sdECFHXgMJkV6zkMN9AT57HE8',
    appId: '1:769073984988:ios:d0dc31bc196abdcca40b19',
    messagingSenderId: '769073984988',
    projectId: 'novelora-project',
    storageBucket: 'novelora-project.firebasestorage.app',
    iosBundleId: 'com.novelora.app.noveloraMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvXY-qT2sdECFHXgMJkV6zkMN9AT57HE8',
    appId: '1:769073984988:ios:d0dc31bc196abdcca40b19',
    messagingSenderId: '769073984988',
    projectId: 'novelora-project',
    storageBucket: 'novelora-project.firebasestorage.app',
    iosBundleId: 'com.novelora.app.noveloraMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhnepo17M88QhxDOlL3aI06qVdjmLHKZg',
    appId: '1:769073984988:web:6228e127eb8b2443a40b19',
    messagingSenderId: '769073984988',
    projectId: 'novelora-project',
    authDomain: 'novelora-project.firebaseapp.com',
    storageBucket: 'novelora-project.firebasestorage.app',
    measurementId: 'G-FYP2T9HWEW',
  );
}
